# Generated by Django 2.2.2 on 2019-08-27 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwrcApp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processe',
            old_name='user_msisdn',
            new_name='sim_msisdn',
        ),
    ]
