# Generated by Django 2.2.2 on 2020-02-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwrcApp', '0003_auto_20190828_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente_unitel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_sap_reference', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AGENTE_UNITEL',
            },
        ),
        migrations.RenameField(
            model_name='config_propertie',
            old_name='key1',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='mobile_propertie',
            name='key1',
        ),
        migrations.AddField(
            model_name='mobile_propertie',
            name='key',
            field=models.CharField(default=1, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
