# Generated by Django 2.2.2 on 2020-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwrcApp', '0006_agente_unitel_alarm_config_propertie_eai_cdr_mobile_propertie_operation_processe_product_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id_utiizador', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('utilizador', models.CharField(max_length=255)),
                ('senha', models.IntegerField(primary_key=True, serialize=False)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataModificacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
