# Generated by Django 2.2.2 on 2020-04-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwrcApp', '0007_utilizador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agente_unitel',
        ),
        migrations.DeleteModel(
            name='Alarm',
        ),
        migrations.DeleteModel(
            name='Config_propertie',
        ),
        migrations.DeleteModel(
            name='Eai_cdr',
        ),
        migrations.DeleteModel(
            name='Mobile_propertie',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.DeleteModel(
            name='Processe',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sms',
        ),
    ]
