# Generated by Django 2.2.2 on 2020-04-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwrcApp', '0008_auto_20200404_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente_unitel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_sap_reference', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AGENTE_UNITEL',
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('alarm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'alarms',
            },
        ),
        migrations.CreateModel(
            name='Config_propertie',
            fields=[
                ('module', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('module_id', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'config_properties',
            },
        ),
        migrations.CreateModel(
            name='Eai_cdr',
            fields=[
                ('eai_cdr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('process_id', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(max_length=255)),
                ('eai_error_code', models.CharField(max_length=255)),
                ('eai_error_message', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('processor_id', models.CharField(max_length=255)),
                ('operation_id', models.IntegerField()),
                ('eai_cdr_history_id', models.CharField(max_length=255)),
                ('guid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'eai_cdr',
            },
        ),
        migrations.CreateModel(
            name='Mobile_propertie',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'mobile_properties',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('operation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('process_id', models.IntegerField()),
                ('operation_type', models.CharField(max_length=255)),
                ('retry_count', models.IntegerField()),
                ('retry_interval', models.IntegerField()),
                ('base_request_id', models.CharField(max_length=255)),
                ('id_processor', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('operation_history_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'operation',
            },
        ),
        migrations.CreateModel(
            name='Processe',
            fields=[
                ('process_id', models.IntegerField(primary_key=True, serialize=False)),
                ('end_of_upload_received', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('sim_status', models.IntegerField()),
                ('sim_type', models.IntegerField()),
                ('lrw_session_id', models.CharField(max_length=255)),
                ('urd_session_id', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=255)),
                ('doc_number', models.CharField(max_length=255)),
                ('doc_name', models.CharField(max_length=255)),
                ('alternative_contact', models.CharField(max_length=255)),
                ('lrw_lac', models.CharField(max_length=255)),
                ('urd_lac', models.CharField(max_length=255)),
                ('lrw_cell_id', models.CharField(max_length=255)),
                ('urd_cell_id', models.CharField(max_length=255)),
                ('agent_sap_reference', models.CharField(max_length=255)),
                ('guid_gwrc', models.CharField(max_length=255)),
                ('guid_kta', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('sim_msisdn', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('process_history_id', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'processes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('sms_id', models.IntegerField(primary_key=True, serialize=False)),
                ('process_id', models.IntegerField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('date_replyed', models.DateTimeField(auto_now_add=True)),
                ('originator_msisdn', models.CharField(max_length=255)),
                ('originator_ip', models.CharField(max_length=255)),
                ('proxy_id', models.CharField(max_length=255)),
                ('network_node_id', models.CharField(max_length=255)),
                ('operation_type', models.CharField(max_length=255)),
                ('request', models.CharField(max_length=255)),
                ('reply', models.CharField(max_length=255)),
                ('error_code', models.CharField(max_length=255)),
                ('sms_history_id', models.CharField(max_length=255)),
                ('imei', models.CharField(max_length=255)),
                ('app_version', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sms',
            },
        ),
    ]
